export const CHATBOT_INTENCOES = [
	'OBTER_CLIENTE_POR_ID',
	'OBTER_ORDEM_SERVICO_POR_NUMERO',
	'OBTER_FUNCIONARIO_POR_ID',
	'OBTER_ORDEM_SERVICOS',
	'OBTER_CLIENTES',
	'OBTER_FUNCIONARIOS',
	'OBTER_TIPOS_SERVICOS',
	'OBTER_TIPO_SERVICO_POR_ID',
] as const
